### ISSUE TITLE
Sprint Goal: 01 June 2023 - 14 June 2023

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#1007]
Expected Business Outcome:

Load Testing
Documentation for HLV2 Pipeline
80% automated test coverage on Structural Validator, MMG Validator and Lake of Segments Transformer
Implementation of PHLIP messages
Incorporate Hepatitis V2.0 MMG
Prepare for DEMO Days (6/22)

Goal : Features

- [ ] Performance testing on Test environment 
- [ ] Documentation for Program Users #971
- [ ]  MMG-VALIDATOR: Add unit test for function call and coverage report #888
- [ ] Add PHLIP Flu and PHLIP VPD use case to HL7 pipeline (ELR)#518
- [ ] Improve Validation Report Table schema #961
- [ ] Test Validation Report Table #963
- [ ] Incorporate Hepatitis MMG v2.0 into pipeline #695 (would like to show on June 22nd as part of demo day)
- [ ] GENv1 HL7 Validations: QA-ReqID 00026 - error not returned when OBR-4 does not have literal value per PHIN Spec. #945
- [ ] GENv1 HL7 Validations: Blanket DT Processing: Updates needed for DEX#943
- [ ] Design Logging mechanism to cope with message traceability#282
- [ ] Implement consistent logging for all functions and services#236
- [ ] CDH AWS S3 to DEX - Pull Initial Data Test#990

Stretch Goals
- [ ] Sample Data Quality Queries to share with Programs #674
- [ ] Load Production Messages (Case) by payload date #962
