### ISSUE TITLE
Sprint Goal: 01 June 2023 - 14 June 2023 (Lab)

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#1008]
Expected High Level Business Outcomes:

Make at least one data product available for COVID ELR (e.g., Lake of Segments or other)
Move closer to production by having a separate TST and STG environments
Maintenance of ELR transitioned to Accenture by June 15, 2023
Finalized Data provisioning (based on JSON provided by Kiran)

Carry over from Last Sprint

 - [ ] QA/Testing of data model(s) with iterative changes incorporated based on customer feedback
 - [x] QA/testing of validation of ELR messages with COVID program (e.g., aiming for parity)
 - [ ] 80% automated test coverage on Structural Validator, MMG Validator and Lake of Segments Transformer
 - [ ] Incorporate changes to the COVID ELR schema based on the JSON provided by Kiran

 Sprint Features

- [ ] Create FunctionConfig for Lake-of-Segments and move "static" info to it.#1017
- [ ] Create FunctionConfig class for Structure-Validator and move "static" info to it.#1016
- [ ] Create FunctionConfig class for Redactor and move "static" info to it.#1015
- [ ] Create FunctionConfig for HL7-Json-Lake Fn and move static code to it.#1018

Stretch Goal
- [ ] SPIKE: VALIDATION-API (synchronous)#983
- [ ] Test with production data
- [ ] Test with real sender
- [ ] Test Message transformer for Lake of Segments model #608

Ops related:

- [ ] CI/CD or dev/tst/stg/prod or HL7v2 pipeline
- [ ] Deploy HL7 IAC to DEX Prod with EDAV Prod integration
- [ ] Implement infrastructure reqs to support PHIN MS AWS S3 feeds to DEX Prod storage
