### ISSUE TITLE
Sprint Goal: 15 June 2023 - 28 June 2023

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#1045]
Expected Business Outcome:

Load Testing
Documentation for HLV2 Pipeline
80% automated test coverage on Structural Validator, MMG Validator and Lake of Segments Transformer
Implementation of PHLIP messages
Test Hepatitis V2.0 MMG 
Prepare for DEMO Days (6/22)
Parity between DEX validation (NIST IGAMT, MMG) with current validation (e.g., MVPS), including documentation of any differences

Goal : Features

- [x] Performance testing on Test environment 
- [ ] Documentation for Program Users #971
- [ ] Add PHLIP Flu and PHLIP VPD use case to HL7 pipeline (ELR)#518
- [ ] Improve Validation Report Table schema #961
- [ ] Test Validation Report Table #963
- [ ] Test Hepatitis V2 in the pipeline #1046
- [ ] Test for Parity between DEX validation (NIST IGAMT, MMG) with current validation (e.g., MVPS), including documentation of where diffs occur #1042

Stretch Goals
- [ ] Sample Data Quality Queries to share with Programs #674
- [ ] Load Production Messages (Case) by payload date #962
