### ISSUE TITLE
Sprint Goal: 3-16 Nov 2022

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-hl7#208]
### Pipeline
Implement "MMG Processor" function to generate MMG-Based Model.
Reference: Data Exchange File Formats Pros and Cons v2 updated 2022-09-20.pptx

Includes
- [x] Structure Validation: PHIN Spec 2.0, 3.0 and 3.1
- [ ] MMG Validation using Table lookup: GenV2 + Lyme/TBRD (MSH21[3] = Lyme_TBRD_MMG_V1.0)
  * [x] Creation of table in Excel #135 
  * [x] Table is machine readable from Redis by the MMG Validator
  * [ ] Update MMG validation code to use #258
- [ ] MMG Processor #32
  - [x] GenV2 + Lyme/TBRD (MSH21[3] = Lyme_TBRD_MMG_V1.0)
  - [x] Original scope: Read 2x MMG from file 
  - [x] Added scope: Build in capability to dynamically pull all MMGs from Redis
  - [ ] Finalize MMG Based model based on Phin Spec for SN, CE, etc...
  - [ ] Finalize event hub ok conforming to new metadata structure #319
  - [ ] Finalize event hub errors conforming to new metadata structure
  - [ ] Pull Vocab from Redis and add to Model
- [X] Metadata #105
- Storage in EDAV
  * [x] 1st choice: DEX Storage Account
  * ~2nd choice / backup: General Storage Account~
- Format
  * [x] 1st choice: Show in Databricks
  * 2nd choice: Show a JSON in ADLS storage

Excludes
- PHIN Spec 3.2
- MMG: Legacy (Arbo), GenV1 by itself, GenV2 by itself, ~GenV2 + Lyme~
- Redactor service
- Deduplicator service
- Lab template
- Repeating MMG Model segments in a different table

#### Metadata
- [ ] Databricks code PR'd into data-exchange-hl7 subfolder
- Metadata views in Databricks
  * Structure Validation
  * MMG Validation
