### ISSUE TITLE
Output to Program Analytics: Build different options for presenting data to the Lyme pilot team

### ISSUE THREAD

**Issue by dcdlz** [CDCgov/data-exchange-hl7#23]
HL7 Build Team needs to provide different options to the Lyme program for obtaining their data from Data Exchange.  We must start with a list of options based on our knowledge of program needs.  We will iterate based on feedback at a future meeting with the program, TBD.  

Lyme data comes in under two different formats - GenV1 message (where the condition code has to be read for Lyme/TBRD conditions) or under the Lyme MMG (where GenV2 is appended and sent along with it).  

The initial options include:

- [ ] "Lake of Segments": Present the data as a lake of segments.  <This solution carries over some HL7v2 paradigms while being queryable.  Easier to work with than HL7v2 files but still will need transformation before it can be analyzed.> 

- [ ] "MMG-based Model (JSON)": Present the data as a JSON document w/hierarchy representing repeating fields and repeating groups. 
<This option likely to be lossy. This can be designed to keep local codes in OBX 5 fields to reduce loss. Not analyzable as-is and would need some flattening. However, some downstream teams may find this format much easier to work with, much easier to transform, and more straightforward than the lake model. JSON can natively be brought into web applications and displayed on a screen. 

- [X] ~Present the MMG-based data model <our gold table>.~ Merged with above

- [ ] "MMG-based Model (SQL)" Present the data as relational SQL tables in Databricks. Which is a flattened version of the "MMG-based Model (JSON)"
<This is a model where every repeating group is its own table.  Each MMG has a base table and those repeating groups can be joined to the base table if analysis calls for it.  This is not 100% flat and would need some JOINs and other SQL code to flatten it into analytic models.>  There could be two sub-parts to this option:  
  * Option A (Selected): The multi-table option
  * ~Version B: one row per "case" (you have to define "case")~

**Comment by lmcnabb** [comment]
@mscaldas2012  Would you add some details to "MMG-based data model - our gold table"?  Can you describe enough so the rest of the team knows the work that would have to be done, if  it is in addition to any work that Cosmin & others are already doing in re-writing everything?  If it's part of that work then no need to make separate issue here for it, will just leave in the list with a checkbox.
