### ISSUE TITLE
Sprint Goal: 17-30 Nov 2022

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#230]
~Tentative demo at the end of the sprint~
Sprint Goal: Demonstrating a message through the entire pipeline and landing in Databricks in the _MMG-based model_

Previous Sprint Goal: Showed EventHub payload after transformer, and without PreferedConceptName.

**Validation (for HL7v2 Case Notification)**
- [x] MMG Validation using Table lookup: GenV2 + Lyme/TBRD (MSH21[3] = Lyme_TBRD_MMG_V1.0)
  * [x] Update MMG validation code to use #258
- [x] MMG Processor #32
    * [x] Finalize MMG Based model based on Phin Spec for SN, CE, etc...
    * [x] Finalize event hub ok conforming to new metadata structure #319
    * [x] Pull Vocab from Redis and add to Model
    * Finalize event hub errors conforming to new metadata structure ==> Moved to next sprint, #344

**Databricks**
- [x] Databricks code PR'd into ~data-exchange-hl7 subfolder~ repo:data-exchange-hl7-dbx
- [x] Metadata views in Databricks
  - [x] Structure Validation
  - [x] MMG Validation
  - [x] MMG-based model ~to SQL~ #324

**Ops**
- CI/CD 
- Atlantis for terraform automation
- Stretch: Grafana (in waiting status on Microsoft)
- Stretch: Start work on SQL model
