### ISSUE TITLE
Sprint Goal: 1-14 Dec 2022

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-hl7#300]
**Sprint Goal**: Demonstrating a Lyme message through the entire pipeline and landing in Databricks in the _MMG-in-SQL model_
   Previous Sprint Goal: Demonstrating a Lyme message through the entire pipeline and landing in Databricks in the _MMG-based model_

Open questions
- Do you want your data engineer to start consuming the MMG-based model in Databricks, or wait for the MMG-in-SQL model to be available?  _Programs want MMG-in-SQL model._
- How to show warnings alongside data in the data product (Lake of Segments, MMG-based, MMG-in-SQL)?
- Our understanding is your preference is to use the MMG-based model. How would you like to handle non-mapped data elements in the MMG?
  * ~Option A: Append non-mapped segments into "MMG-based model", even though they aren't apart of MMG?~
  * Option B: Pick-up your non-mapped segments from the lake of segments? ==> Selected by Lyme/Arbo on 2022-11-30

### Goal
**MMG Transformer > MMG-based model**
- ~MMG Transformer > MMG-based to push to 2 Event Hub Queues downstream #344~ ==> Carry over to next sprint

**MMG Transformer > MMG-in-SQL model**
- [x] MMG Transformer > SQL to push to 2 Event Hub Queues downstream #369

**DEX Consumption routing**
- [x] Design for how to route just the conditions a program cares about to that program #354 
- Implementation to show the program just their messages #355 
  - [X] Updating metadata in library
  - Using the library update to put condition information in reciever-debatcher ==> Next sprint
  - Actually use the reciever-debatcher metadata to route a message ==> Next sprint / out of scope for this sprint

**Databricks**
- [X] ~Dynamically flatten the MMG-based model to the MMG-in-SQL model~ OBE (overcome by events). Moved functionality from Databricks to fn-mmg-sql-transformer. #369
- [X] Metadata summary view for Structure validator and MMG validator result
  - [X] 1. Consuming EventHub topics in Databricks #33
  - [X] 2. String --> Databricks Bronze table #178
  - [X] 3. Visualize Databricks Bronze table #178

**Ops**
- [ ] Create a container instance for Atlantis within the DEX ACR #289 ==> Ask @boris-ning-usds 
- [x] Create 4 new Event Hub Topics #343

**Other / Tech debt**
- [x] Receiver-debatcher needs bad messages pushed to Eventhub failure queue #78 (carryover from previous sprint)
- [x] Create function to populate condition code tables in Redis #257 (carryover from previous sprint)
- [x] Update README.md in sub-projects folders
  - [x] lib-dex-common
  - [x] lib-nist-validator
  - [x] Receiver/Debatcher
  - [x] Structure Validator
- [x] Make the MMR sub-folder structure the same as fns-hl7-pipeline sub-folder structure  @dtx0111 #257 
  * https://github.com/CDCgov/data-exchange-hl7/tree/develop/mrr/src/main 
  * https://github.com/CDCgov/data-exchange-hl7/tree/develop/fns-hl7-pipeline/fn-message-processor/src/main 

### Stretch
- [ ] Implement consistent logging for all functions and services #236, #282

Demo at next Sprint Review:  Hepatitis test messages from drop to MMG-based model.
