### ISSUE TITLE
Sprint Goal: 15-28 Dec 2022

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-hl7#309]
NB: Reduced time due to the holidays (Have a merry Christmas, Happy Hannukah, Happy Kwanzaa!). Really 1/2 a sprint.

## Goal
Transformers
- [x] MMG-based: MMG-based Transformer > Push to 2 Event Hub Queues downstream #344 (from last sprint) 
- [x] MMG-SQL: MMG-SQL-Transformer > Push to 2 Event Hub Queues downstream #404
- [x] MMG-in-SQL: Any additional features in fn-mmg-sql-transformer
- [x] Rename ConditionCode class on Message Processor #327
- [x] Update loadEventMaps () function to use Condition2MMGMapping class #385
- [ ] "Azure Data Explorer Dashboard": Add mmg-in-sql eventhubs to Azure function "dashboard"

Databricks
- [ ] Databricks: Add Notebook? View? to visualize results of  fn-mmg-sql-transformer in Databricks
- [x] Show in SQL DB view #408

Bugs
- [x] #391, #399, #392, #388

Ops
- [x] Create new functions due to renaming by Ops team #371
- [x] Create appropriate consumer groups for all Event Hubs #389

Consumption routing
- [x] Using the library update to put condition information in reciever-debatcher (from last sprint #300)
- [ ] Actually use the reciever-debatcher metadata to route a message (carried forward into Dec29-Jan11 Sprint)

## Stretch
