### ISSUE TITLE
Sprint Goal: 29 Dec 2022 - 11 Jan 2023

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-hl7#368]
NB: This is really 3/4s of a sprint because of the holidays.  Happy New Year!  It's 2023!!!!

## For review
(pending acceptance by devs)
- Cosmin shows Lyme/Arbo his progress on the MMG-in-SQL (in terminal; not Databricks)
- Marcia reviews "Blanket Processing" list with customer. Will NOT be a separate service. Shows what has been done, what remains to be done.

## Goals
- [x] refactor MRR functions for multiple triggers (#435)(hookup redis event to functions)
- [x] discovery and design additional validation for the lab template after structural validation (#387) 
- [x] update message_info "route" value to use the name of the most specific MMG instead of the profile name (#441)
- [x] fn-mmg-sql-transfomer -> message_profile_identifier to flat model and not in tables (#444)
- [x] implement consumption routing of transformed messages to programs (#355)
- [ ] design Logging mechanism to cope with message traceability (#282)
- [ ] Integration of blanket processing rules into MMG Validator (#195)
- [ ] Develop Message Transformer for Lake of Segments (#175)

- [ ] Rename ConditionCode class on Message Processor (renamed to MMG-Based-Transformer) (#327)

Databricks:
- [x] refactor DBx notebook structure (#415)
- [x] create summary view for structural validation and mmg validation in dbx (#178)
- [x] metadata work (include warning and error counts in bronze tables) and create silver tables (#436)
- [ ] Create a normalized delta table for structure-err event hub metadata (#431)
- [ ] Azure Eventhub to DBx Table Mappings (#380)

Tech Debt:
- [x] update NIST to latest version (#424) 
- [ ] Debug NIST issues on the latest Release (#453)

Ops-related:
- [x] create new EventHubs due to renaming by Ops team (#343)
- [x] Working session and implement changes to due to Ops changes (#414) 

Bugs:
- [x] bug fix (structure error report returning null on error-count) (#413) 

## Stretch
