### ISSUE TITLE
Quarterly Goal: FY23 Q2 (Jan - Mar 31) - HL7v2 

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#375]
FY2023-Q2 Goals: Get the validation results and data products to Lyme/Arbo/Hep

For FY2023-Q2 we have as main goals to have a complete HL7 pipeline with all functionality implemented; integrate our pipelines with existing data sources containing raw data: PHINMS, sftp, SDX, and AWS S3; integrate our solution with CDC's Enterprise Data Catalog and have our outputs available and cataloged by the EDC team; and flush out data governance of our data products and program access.

Itemized list: 
- [x] Finalize HL7 pipeline with to-be-developed functionality:
   * [x] Redaction (for case)
   * [ ] Support for Lab Template data
   * [x] Provide Lake-of-segments data product to programs
   * [x] Implement blanket processing rules

- [x] Interoperability with existing HL7 case data stream
  * [ ] Receive data from existing raw data sources
     * [x] PHINMS
     * [ ] AWS S3  
  * [x] Code changes and integration, where required, to support requirements from discovery meetings with NNDSS - TBD.

- [ ] Finalize Data governance and consumption routing in Data Bricks for program access.

---------------------
- [ ] Stretch Goals
  ~[ ] Exact match de-duplication~
  * [ ] Replay of messages 
  * [x] Build more MMGs into the pipeline
  ~[ ] Integrate with EDC~

---------------------
** DevSecOps Q2 **
Support the DEX HL7 team's Q2 development.
[GSA CoE Cloud Reengineering FY23 Q2 Charter](https://cdc.sharepoint.com/:w:/r/teams/CDC-Data-Exchange/Shared%20Documents/Operations/DevOps/WS-5%20Charter%20-%20FY2023%20-%20Q2.docx?d=w034bbc2354a34fcd8fb14ed5ce5ff36d&csf=1&web=1&e=MVj04e)

** DevSecOps Q2 Goals**
- [ ] Provide the HL7 DEX team with a staging environment to facilitate sprint demos
- [x] Infrastructure as Code built for 100% of cloud infrastructure
  - [x] Development env
  - [ ] Staging env
  - [x] Test env

** DevSecOps Dependencies **
- HL7 technical direction
- CST/OHMS - resource groups, vnets, subnets, ECPaaS, Akamai WAF
- Active Directory - DNS endpoints, AAD groups
- CSPO/Firewall - Splunk, DMZ, Firewalls, ZScaler
- ISSO/Security Steward - CR approval; security guidance; approval workflow
- EDAV - Databricks provisioning, endpoints

** DevSecOps Stretch Goals **
- [ ] Continuous Integration (CI) pipeline set up with manual deployments (app codebase, static/dynamic scans, integration with scanning tools in use)

** DevSecOps Assumptions **
- Terraform automation will be completed by end of December 2022
- HL7 DEX team can demo using a staging environment until a test environment is set up

** DevSecOps Out of Scope for this quarter **
- Infrastructure as Code built for 100% of cloud infrastructure - Production env
- Continuous Delivery (CD) pipeline set up to dev/stg/tst/prd
- DEX runbook created and updated
