### ISSUE TITLE
Sprint Goal: 9 - 22 Feb 2023

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#541]
Expected Business Outcome:

Build Redactor function step
Build Lake of Segments Model

### Goals: Features
- [x] Create a redaction function to be used across all HL7 streams (#508)
- [x] Message transformer for Lake of Segments model (#175)
- [ ] Implement the HL7 data feed from PHIN MS into DEX (#499)
- [x] Define redaction process and warning text (#216)
- [x] Create a redaction config for case notifications (#111)

### Goals: Non-functional requirements and Enhancements
- [x] Determine how to read Event Hub metadata on AZ functions (#428)
- [ ] Security coordination around ATO process for DEX (#242) @lmcnabb 
- [ ] Create a test plan (#510) @manandappa 
- [x] Add RunOnStart=true to all 3 cache loader functions (#520) - decided not to do and moved to closed
- [x] Configure EDAV DEV DBX to point to Staging Env in PROD Subscription (#519)
- [ ] Create KeyVaults for each env (#46)
- [x] Add new column Classification to Validation Silver tables (#54)
- [ ]  Create some GenV2 test messages (#531)

### Goals: Tech Debt and Bugs
- [ ] Redis cache is empty of data sometimes (#432)
- [x] Remove dots from MMG names (#474)
- [x] MMG Validator: Catch NoSuchElementException when MSH-21 is Empty (#536)

### Stretch Goal
- [ ] Error Queue Pipeline: incl rec-deb, mmg-based-err, and mmg-sql-err dbx notebooks (#544)
