### ISSUE TITLE
Sprint Goal: 23 Feb - 8 March 2023

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#542]
Expected Business Outcome:

Complete and test Redactor function 
Complete and test Lake of Segments Model
Add Mumps, Pertussis and Covid MMGS
Fix issues found related to HL7 Validation
Sanity checks for Vocabulary/MMG and Meta data is loaded accurately.
HL7 data feed from PHIN MS into DEX
Continue testing the HL7 Validation
Stretch:  Implement Lab Template

### Goals: Features
- [ ] Test redaction function in Case (#607)
- [ ] Test Message transformer for Lake of Segments model (#608)
- [ ] Implement the HL7 data feed from PHIN MS into DEX (#499)
- [ ] Check Vocab Cache if loaded (#571, #432)
- [ ] Implement Mumps/Pertussis and Covid MMG in DEX (#504, #505, #502)
- [ ] Blanket Rule Processing (#545), Date Validation (#537)
- [ ] Discovery/planning around implementation of lab template in pipeline (#307)

### Goals: Non-functional requirements and Enhancements
- [x] Security coordination around ATO process for DEX (#242) @lmcnabb 
- [x] Create a test plan (#510) @manandappa 
- [x] Create KeyVaults for each env (#46)
- [ ]  Create  GenV2 test messages (test bank to validate (#531)
- [x]  Create Gen V1 test messages (#609)
- [ ] Update MMG transformer to cope w/multiple values on fields with Cardinality [?..1] (#552)
- [ ] Update Redactor function to process ELR messages (#621)

### Goals: Tech Debt and Bugs
- [ ] Redis cache is empty of data sometimes (#432, #571)

### Stretch Goal
- [ ] Error Queue Pipeline: incl rec-deb, mmg-based-err, and mmg-sql-err dbx notebooks (#544) 

### Issues added during Sprint
- [x] Hep program wants to run Python code (#647)
- [x] Redaction - NK1 not being redacted (#684)
- [x] MMG-SQL Gold Notebook is failing when route is 'NoneType' (#78)
- [x] 'NoneType' check update on gold notebooks (#84)
- [x] Add Summary to the payload on Redactor function (#678)
- [x] Create notebook to generate raw and bronze tables for Redactor Event Hubs (#71)
- [x] Update Redactor Report Structure to Map of entries (#659)
- [x] Structure Validator event hubs data is not down streaming in DBX (#640)
- [x] Fix MMG-based Transformer bug w.r.t. Hep MMGs (#663)
- [x] fn-mmg-sql-transformer giving "condition not found" exception for Varicella (#641)
- [x] fn-mmg-based-transformer update to process legacy MMGs w/no EPI OBR (#624)
- [x] Set up new TEST env (#56)
- [x] Create KeyVaults for each env (#46)
- [x] Need to add cloud groups to ZScaler Firewall (#639)
- [x] Create AD Windows Group (#677)
- [x] Add list of users to new cloud groups (#649)
- [x] ZScaler entitlements group setup by cloud team (#630)
- [x] Need Cloud groups for DataOps and SecOps (#637)
- [x] Need Cloud groups for DevOps and CELR team (#636)
- [x] Add widget for DBX scope (#93)
- [x] Missing jurisdiction info for CELR ELR  (#592)
- [x] Bump groovy version in /local_libs/lib-bumblebee (#688)
- [x] Implemented error queue pipeline (#97)
