### ISSUE TITLE
Sprint Goal: 9 -22 March 2023

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#610]
Expected Business Outcome:

Fix issues found related to HL7 Validation
Focus on creating a stable environment
Continue with HL7 Validation (based on PHIN Spec)
Test GEN V1, Arbo, Varicella messages
Sanity checks for Vocabulary/MMG and Meta data is loaded accurately.
Test the Pipeline (Errors/Warnings)
HL7 data feed from PHIN MS
Start on Documentation for Programs

### Goals: Features

Carry-over from previous sprint:
- [x] Blanket Rule Processing (#545), Date Validation (#537)
- [x] Check Vocab Cache if loaded (#571, #432)
- [ ] Implement the HL7 data feed from PHIN MS into DEX (#499)
- [x] Update MMG transformer to cope w/multiple values on fields with Cardinality [?..1] (#552)
- [x] Update Redactor function to process ELR messages (#621)

New to this sprint 

- [ ] GENv2 HL7 Validations: Blanket DT Processing: Updates needed for DEX (#667)
- [x] Redaction - NK1-4.2 value is not redacted. #689
- [x] Redaction - Additional Usage X fields for NK1 missing from config file. #687
- [x] Structure validator not populating metadata properly when exception is thrown #693
- [ ] GENv2 HL7 Validations: Blanket Processing: ReqID 00026 - Update the error message when OBR-4 is incorrect. Error is not coming from MMG Validator #555
- [ ] Test Databricks tables to make sure errors and warnings are populated as expected #587
- [ ] Validate GEN V1, Varicella, Arbo messages #644

### Stretch Goal
- [ ] Incorporate one MMG (Mumps, Pertussis)
- [ ] Documentation for Program Users (#671)
~- [ ] Sample Data Quality Queries to share with Programs (#674)~
- [x] Discovery/planning around implementation of lab template in pipeline (#307)
- [ ] Test Message transformer for Lake of Segments model (#608)
