### ISSUE TITLE
Normalize Processes name and status

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#612]
Each function appends a ProcessMetadata to processes array. Right now, processes name and status are all over the place.

This ticket is to remove this Tech. Debt and use standard naming convention and statuses.

- [ ] #613
    Should be treated as a constant and therefore should be named all CAPITAL with underscore separation.
    The following names should be used:
    - [x] RECEIVER
    - [x] REDACTOR
    - [x] STRUCTURE_VALIDATOR
    - [x] MMG_VALIDATOR
    - [x] MMG_BASED_TRANSFORMER #871 
    - [ ] MMG_BASED_SQL_TRANSFORMER #872 
    - [x] LAKE_OF_SEGMENTS_TRANSFORMER #873 

(While we're at it - make the function name the same as the Process name)

- [ ] Process Status:
   It should indicate whether the process was successful or if failed. Period. The explanation of the Failure should be on the PROBLEM attribute. A failure can be business related - did not pass validation - or a infrastructure related - unable to access other AZ resources.
   valid values: SUCCESS or FAILURE

   - [ ] Redactor (need to create a processMD when exception is thrown)
   - [ ] Structure_validator
   - [ ] MMG_Validator
   - [ ] MMG_Based_Transformer #871
   - [ ] MMG_SQL_Transformer #872
   - [ ] Lake_of_segments #873
