### ISSUE TITLE
Sprint Goal: 23 Feb - 8 March 2023

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#616]
Expected Business Outcome:
Evaluate/Implement Conformance Profiles for ELR 
Implementing a SVC Transport to upload files with METADATA (this will cover AIMS naming convention)
Embed ELR logic into Pipeline;
Receiver/Debatcher : consume transport metadata for message identification
Redactor: apply appropriate config for ELR vs Case
Structure Validator: Load COVID Profiles and apply appropriate profiles for ELR vs Case.

### Goals: Features

- [ ] Implement svc-cloud-transport. #601
- [ ] Enhance Receiver-Debatcher support lab messages #532
- [ ] Update Redactor function to process ELR messages #621
- [ ] Create a redaction config for the "lab notifications" use case #534
- [ ] Create Configuration file to drive Profiles to use for structure validation #560
- [x] Missing Jurisdiction Information in CELR ELR #592
