### ISSUE TITLE
Sprint Goal: 23 March - 5 April 2023

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#722]
Expected Business Outcome:

Fix issues found related to HL7 Validation
Continue with HL7 Validation (based on PHIN Spec)
Test GEN V1, Arbo, Varicella messages
Sanity checks for Vocabulary/MMG and Meta data is loaded accurately.
Test the Pipeline (Errors/Warnings)
HL7 data feed from PHIN MS (dependency:  getting ATO)
Obtain ATO (dependency: OCIO/ISSO/CSPO)

### Goals: Features
- [ ] Complete testing/fixing issues with HL7 Validations
- [ ] Databricks table/view with consolidated view on errors/warnings CDCgov/data-exchange-hl7-dbx #126
- [x] MMG Validator: Add process object to Exception block CDCgov/data-exchange-hl7 #731
- [x] MMG Validator: Update to lib-dex-commons latest snapshot CDCgov/data-exchange-hl7 #730
- [x] Include Process object when MMG Validator throws an error CDCgov/data-exchange-hl7 #697
- [x] Update Summary metadata on Redactor CDCgov/data-exchange-hl7 #721
- [x] Structure validator not populating metadata properly when exception is thrown CDCgov/data-exchange-hl7 #693
- [x] Incorporate three MMGs (Mumps, Pertussis, Varicella)

Carry-over from previous sprint:

- [x] Implement the HL7 data feed from PHIN MS into DEX (#499)
- [ ] GENv2 HL7 Validations: Blanket DT Processing: Updates needed for DEX (#667)
- [x] Test Databricks tables to make sure errors and warnings are populated as expected CDCgov/data-exchange-hl7#587
- [ ] Validate GEN V1, Varicella, Arbo messages CDCgov/data-exchange-hl7#644

### Stretch Goal

- [ ] Documentation for Program Users (#671)
- [ ] Sample Data Quality Queries to share with Programs (#674) - Marion and John C
- [ ] Test Message transformer for Lake of Segments model (#608)
