### ISSUE TITLE
Sprint Goal: 23 March - 5 April 2023

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#723]
Expected Business Outcome:

Testing pipeline for ELR

### Goals: Features
- [ ] Start Testing pipeline for ELR #734
- [ ] Update Structure validator to use different Event Hubs for CASE vs ELR messages #736
- [ ] Normalize Processes name and status #612

Carry-over from previous sprint:
- [ ] Modify Lake of Segments FN to consume from multiple Event Hubs (#619)

### Stretch Goal
