### ISSUE TITLE
Sprint Goal: 6 - 19 April 2023

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#749]
Expected Business Outcome:

Fix issues found related to HL7 Validation
Fix issues related to performance.
Get Test environment ready for load testing

### Carry Over from last sprint

- [x] Complete testing/fixing issues with HL7 Validations
 - [ ] Table/view with consolidated view on errors/warnings CDCgov/data-exchange-hl7-dbx [#126](https://github.com/CDCgov/data-exchange-hl7-dbx/issues/126)
-  [ ] GENv2 HL7 Validations: Blanket DT Processing: Updates needed for DEX (#667) --- Needs to test/verify by Nadia
- [ ] Validate GEN V1, Varicella, Arbo messages #644 -- Needs to verify by Nadia

### Goals: Features

- [ ] Re- test HLV2 validation after the DEV team fixes the issues
- [ ] Performance testing of the HL7 validation pipeline (for case) #516
- [x]  Incorporate three MMGs (Malaria, Measles, Rubella, Legacy TB)

### Stretch Goals

- [x] Test Message transformer for Lake of Segments model (#608)
