### ISSUE TITLE
Quarterly Goal:  FY23 Q3 (Apr - June 30) - CASE

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#767]
Expected High Level Business Outcomes:

All MMGs have been loaded into the pipeline and provisioning for the lab template in the MMG-based models is complete. The pipeline can process any NNDSS condition, with or without the lab template.

The HL7v2 pipeline can process, validate and provision data products using all raw sources of HL7 NNDSS data (PHIN MS, AWS S3).

QA/Testing of validation results and data models with Lyme/Arbo/Hep completed.  We have parity with MVPS and where we don't, it's documented.

QA/Testing of scalability and reliability of HL7v2 validation pipeline completed.  We have tested the performance of the pipeline, addressed bottlenecks, and developed benchmarks and metrics for performance.

Ops related:
CI/CD or dev/tst/stg/prod or HL7v2 pipeline
IaC in prod for HL7v2 pipeline
IaC for dev/tst/stg for legacy data streams (PHIN MS and AWS S3)

### Goals: Features
- [ ] All MMGs in production are in the pipeline
- [ ] Parity, where possible, with MVPS validation.  Documentation where there are differences.
- [ ] Pipeline can process raw case data from PHIN MS and AWS S3, on demand and in real-time.

### Goals: Non-functional requirements and Enhancements
- [ ] QA/Testing of scalability and reliability of pipeline with documented performance metrics (e.g., load, performance testing)
- [ ] QA/Testing of data models (Lake of Segments, or other model) with iterative changes based on customer feedback.
- [ ] 80% automated test coverage on Rec-Deb, Redactor, Structural Validator, MMG Validator and Lake of Segments Transformer
- [ ] Create and maintain a separate TST and STG validaiton pipeline

### Stretch Goal
- [ ] Replay functionality
