### ISSUE TITLE
Quarterly Goal: FY23 Q3 (Apr - June 30) - ELR

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#768]
Expected High Level Business Outcomes:

Make at least one data product available for COVID ELR
Redact PII from specified ELR fields before data is provided to programs.
Demonstrate successful validation and provisioning of ELR test messages to COVID program.
Successful transitioning from Peraton to Accenture

### Goals: Features

- [ ] Create a data product for COVID ELR that meets program needs
- [ ] Create a separate Test environment for ELR 
- [ ] Complete testing the validation in the pipeline for ELR
- [ ] Complete testing the provisioning for ELR
