### ISSUE TITLE
Sprint Goal: 20 Apr - 03 May 2023

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#842]
Expected High Level Business Outcomes:

Make at least one data product available for COVID ELR (e.g., Lake of Segments or other)
Move closer to production by having a separate TST and STG environments
Maintenance of ELR transitioned to Accenture by June 15, 2023

###  Carry over from Last Sprint
 - [ ] Start Testing pipeline for ELR #734
 - [x] Update Structure validator to use different Event Hubs for CASE vs ELR messages #736
 - [x] Normalize Processes name and status #612
- [x] Modify Lake of Segments FN to consume from multiple Event Hubs (#619)
### Goals: Features
- [ ] Demonstrate successful validation and provisioning of ELR test messages to COVID program
- [x] ELR has its own redaction profile implemented into pipeline
- [x] Pipeline can differentiate and process different HL7v2 messages

### Goals: Non-functional requirements and Enhancements
- [ ] QA/Testing of data model(s) with iterative changes incorporated based on customer feedback
- [ ] QA/testing of validation of ELR messages with COVID program (e.g., aiming for parity)
- [x] 80% automated test coverage on Rec-Deb, Redactor, ~Structural Validator, MMG Validator and Lake of Segments Transformer~
- [x] Create and maintain a separate TST and ~STG validaiton pipeline~

### Stretch Goal
- [ ] Test with production data 
- [ ] Test with real sender

Ops related:
CI/CD or dev/tst/stg/prod or HL7v2 pipeline
IaC in prod for HL7v2 pipeline
IaC for dev/tst/stg for legacy data streams (PHIN MS and AWS S3)
