### ISSUE TITLE
Receiver-Debatcher: Build Reciever-Debatcher Service for HL7 processing pipeline

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-hl7#86]
### Phase 4
- [x] Integrate to Azure selected database solution (other issue)
- [ ] ~Design and develop message (file) Replay functionality~ #106

### Phase 3
- ~Integrate to Azure Vault~ Injected into FunctionApp config
- ~Integrate to Azure Monitor Log~ out of the box
- [x] Push to Event Hub failure messages
- [ ] Change Event Hub push to batch push for performance (will do under performance testing)

### Phase 2: 2022-11 #78 
- [x] Push to Event Hub failure messages

### Part 1: 2022-09 #29 
- Receives event hub notifications
- Reads (from) JSON notification
- Creates message (file) metadata
- Debatches files into HL7 messages
- Creates and event hub notifications for ok and for failure
- Saves metadata to a database for later replay
- Integrates replay functionality

**Comment by rmharrison** [comment]
@lmcnabb Insert segments to redact, e.g., PID9, PID19

**Comment by lmcnabb** [comment]
@cosmycx and @mscaldas2012 can you guys review this checklist above?  If this meets the criteria of initial dev complete, then let's close it and create another for ongoing or additional work that needs to be done.
