### ISSUE TITLE
Sprint Goal: 04 May 2023 - 17 May 2023

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#896]
Expected Business Outcome:

Get Test environment ready for load testing.
Load Testing
Documentation for HLV2 Pipeline
80% automated test coverage on  Structural Validator, MMG Validator and Lake of Segments Transformer

### Goals: Features
- [x] Performance testing of the HL7 validation pipeline (for case) #516
- ~[ ] Incorporate RIBD~ RIBD is in Icebox (#507)
- [ ] Documentation for Program Users #671
- [ ] MMG-VALIDATOR: Add unit test for function call and coverage report #888
- [x] STRUCTURE-VALIDATOR: Add Unit test for function call and coverage report #887
- [x] Enum HL7MessageType has misspelled entry "UNKOWN"#786

### Stretch Goals
- [ ] Validate message against the FULL Spec #844
- [ ] Sample Data Quality Queries to share with Programs #674
