### ISSUE TITLE
Sprint Goal: 18 May 2023 - 31 May 2023

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#952]
Expected Business Outcome:

Load Testing
Documentation for HLV2 Pipeline
80% automated test coverage on  Structural Validator, ~MMG Validator~ and Lake of Segments Transformer
Start on implementation of PHLIP messages

### Goals: Features
- [x] Performance testing on TST environment #939
- [ ] Documentation for Program Users #971
- [ ] MMG-VALIDATOR: Add unit test for function call and coverage report #888
- [x] Conduct discovery on how to include PHLIP Flu and VPD messages in HL7 Pipeline #968
- [ ] Improve Validation Report Table schema #961
- [ ] Test Validation Report Table #963
- [ ] Sample Data Quality Queries to share with Programs #674

### Stretch Goals
- [ ] Load Production Messages (Case) by payload date #962
