### ISSUE TITLE
Sprint Goal: 18 May 2023 - 31 May 2023

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#953]
Expected High Level Business Outcomes:

Make at least one data product available for COVID ELR (e.g., Lake of Segments or other)
Move closer to production by having a separate TST and STG environments
Maintenance of ELR transitioned to Accenture by June 15, 2023
Finalized Data provisioning (based on JSON provided by Kiran)

Carry over from Last Sprint
 - [x] Testing pipeline for ELR #734
- [x] Demonstrate successful validation and provisioning of ELR test messages to COVID program
- [x] Create schema for COVID that could be repurposed for generic ELR#728
- [x] Goals: Non-functional requirements and Enhancements
- [ ] QA/Testing of data model(s) with iterative changes incorporated based on customer feedback
- [ ] QA/testing of validation of ELR messages with COVID program (e.g., aiming for parity)
- [x] 80% automated test coverage on Structural Validator, ~MMG Validator~ and Lake of Segments Transformer
- [x] LAKE-OF-SEGMENTS: Add unit test to the function call and coverage report#889

Stretch Goal

 - [ ] Test with production data
 - [ ] Test with real sender
 - [x] Test Message transformer for Lake of Segments model #608
 
Ops related:
- [ ] CI/CD or dev/tst/stg/prod or HL7v2 pipeline
- [ ] Deploy HL7 IAC to DEX Prod with EDAV Prod integration
- [ ] Implement infrastructure reqs to support PHIN MS AWS S3 feeds to DEX Prod storage
